default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

#development:
#  <<: *default
#  database: porty_development

development:
  <<: *default
  adapter: <%= ENV.fetch("DB_ADAPTER") { 'postgresql' } %>
  url: <%= ENV.fetch("DB_ADAPTER") { 'postgresql' } %>://pipefellow:@<%= ENV.fetch("DB_HOST") {'localhost'} %>/porty_development?pool=5&reconnect=true&encoding=utf8

test:
  <<: *default
  database: porty_test

#production:
#  <<: *default
#  username: deploy
#  password: <%#= Rails.application.credentials[:prod_database_password] %>
#  database: porty_production

production:
  define: &password = <%= Rails.application.credentials[:prod_database_password] %>
  <<: *default
  adapter: <%= ENV.fetch("DB_ADAPTER") { 'postgresql' } %>
  url: <%= ENV.fetch("DB_ADAPTER") { 'postgresql' } %>://deploy:*password@<%= ENV.fetch("DB_HOST") {'localhost'} %>/porty_production?pool=5&reconnect=true&encoding=utf8
